### ISSUE TITLE
Does not work with latest emberjs

### ISSUE THREAD

**Issue by topaxi** [amk221/ember-cli-twitter-entities#1]
This addon won't work with ember as views (including ContainerView) were removed.

**Comment by amk221** [comment]
Correct.. sorry I've neglected this repo whilst I concentrated on upgrading a large Ember app to version 2.

Hopefully I'll be able to re-write this as the weekend

**Comment by topaxi** [comment]
No need to hurry, I just came across this repository and it didn't work :)
